### ISSUE TITLE
Package dependencies are deprecated

### ISSUE THREAD

**Issue by SHAO-Jiaqi757** [henrycg/heavyhitters#1]
error: failed to select a version for the requirement `aesni = "^0.7"`
candidate versions found which didn't match: 0.99.99, 0.10.0, 0.9.0, ...
location searched: crates.io index
required by package `aes v0.4.0`
    ... which satisfies dependency `aes = "^0.4.0"` of package `counttree v0.1.0`

According to https://crates.io/crates/aesni/versions, **`aesni = "^0.7"` is rejected.** 
Moreover, configuring `aes`, `aes-ctr`, `aesni` with the latest version evokes **compile error**: 
* `compile_error!("`aes-ctr` is deprecated. Please switch to `aes`: https://github.com/RustCrypto/block-ciphers/tree/master/aes");`,
* `compile_error!("`aesni` is deprecated. Please switch to `aes`: https://github.com/RustCrypto/block-ciphers/tree/master/aes");`

**Comment by henrycg** [comment]
In commit `8a68a74aad10a020239`, I committed a `Cargo.lock` file that should let you build the binary.
