### ISSUE TITLE
Error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }

### ISSUE THREAD

**Issue by Caovo** [henrycg/heavyhitters#2]
To reproduce your project, in the file 'cargo.toml' I added '[dependencies.openssl] version = "0.10.52" ' and replaced the unsupported certificate 'identity.p12' with a self-signed certificate. But:
$export RUSTFLAGS+="-C target-cpu=native" 
$cargo build --release
    Finished release [optimized] target(s) in 0.13s
$ cargo run --release --bin server -- --config src/bin/config.json --server_id 0
    Finished release [optimized] target(s) in 0.14s
     Running `target/release/server --config src/bin/config.json --server_id 0`
Error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }

**Comment by henrycg** [comment]
Are you using the latest version of the code? Since [9dd191f38d2](https://github.com/henrycg/heavyhitters/commit/9dd191f38d25c1f34ea713510aab3df1c0f6146c), it is not even using TLS between the protocol parties, so the certificate shouldn't matter.

**Comment by Caovo** [comment]
Thank you, I haven't noticed that the project has been updated, and I will contact you if there is any problem.
