### ISSUE TITLE
Experimental related issues

### ISSUE THREAD

**Issue by lwj011** [henrycg/heavyhitters#3]
Hello, may I ask if your code defaults to implementing 128 bit computational security? In the paper, I found that the client runtime is the key generation time, so subtracting the key generation time from the total time is the servers runtime, right?

**Comment by henrycg** [comment]
The computational security parameter is 128 bits. The statistical security parameter (probability that a cheating client can corrupt the result) is set as in Section 8 of the paper.

To get a good measurement of the server runtime, I would measure it directly. There are other costs (e.g., networking costs) that the simple subtraction approach will not capture correctly.

**Comment by lwj011** [comment]
您的邮件已收到～

**Comment by lwj011** [comment]
I'm not quite sure what the time symbol specifically refers to. Is TreeCrawl time+Sketch time for all levels the server runtime？
My output is as follows：
Finished release [optimized] target(s) in 0.23s
     Running `target/release/server --config src/bin/config.json --server_id 0`
Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
    Finished release [optimized] target(s) in 0.25s
leader starting
     Running `target/release/server --config src/bin/config.json --server_id 1`
Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
    Finished release [optimized] target(s) in 0.12s
     Running `target/release/leader --config src/bin/config.json -n 10`
Using only one thread!
Generating keys...
Key size: 7273 bytes
Done.
Generated 10000 keys in 0.628451431 seconds (6.28451431e-5 sec/key)
TreeCrawlStart 0 "-" 7.4e-7
TreeCrawlDone 0 "-" 0.00128292
SketchStart 0 "-" 0.001310788
SketchDone 0 "-" 0.002955606 rate=6104.760125660382
Level 0 active_paths=2 0.003286117
TreeCrawlStart 1 "-" 0.003298638
TreeCrawlDone 1 "-" 0.004180568
SketchStart 1 "-" 0.004201651
SketchDone 1 "-" 0.005750199 rate=6480.746996821842
Level 1 active_paths=4 0.006004959
TreeCrawlStart 2 "-" 0.006018241
TreeCrawlDone 2 "-" 0.006719497
SketchStart 2 "-" 0.006732804
SketchDone 2 "-" 0.007405327 rate=14931.256495096575
Level 2 active_paths=8 0.007641554
TreeCrawlStart 3 "-" 0.007650655
TreeCrawlDone 3 "-" 0.008192975
SketchStart 3 "-" 0.008202854
SketchDone 3 "-" 0.008716038 rate=19587.372412752946
Level 3 active_paths=12 0.008933355
TreeCrawlStart 4 "-" 0.008943763
TreeCrawlDone 4 "-" 0.009432813
SketchStart 4 "-" 0.00944242
SketchDone 4 "-" 0.010284185 rate=11917.445471728244
Level 4 active_paths=16 0.01052154
TreeCrawlStart 5 "-" 0.010535863
TreeCrawlDone 5 "-" 0.010916338
SketchStart 5 "-" 0.01092261
SketchDone 5 "-" 0.011493985 rate=17575.80444456943
Level 5 active_paths=16 0.01170418
TreeCrawlStart 6 "-" 0.011717712
TreeCrawlDone 6 "-" 0.012251388
SketchStart 6 "-" 0.01226496
SketchDone 6 "-" 0.012908368 rate=15613.119391962678
......

**Comment by lwj011** [comment]
Also, if I want to measure communication between two servers, may I ask if there are any related functions provided in your project？

**Comment by henrycg** [comment]
Looking inside the code, you will be able to see exactly which parts of the runtime those measurements capture. For capturing communication cost, you could add some extra code to record and print out the number of bytes exchanged between parties.

**Comment by lwj011** [comment]
Thank you very much for your help.
